[package]
name = "test-parachain-halt"
description = "Test parachain which executes forever"
build = "build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
rustversion = "1.0.6"

[features]
default = [ "std" ]
std = []
