[package]
name = "polkadot-availability-recovery"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
lru = "0.9.0"
rand = "0.8.5"
fatality = "0.0.6"
thiserror = "1.0.31"
gum = { package = "tracing-gum", path = "../../gum" }

polkadot-erasure-coding = { path = "../../../erasure-coding" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem = {path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
parity-scale-codec = { version = "3.4.0", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.9.0"
futures-timer = "3.0.2"
log = "0.4.17"

sp-core = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
