[package]
name = "xcm-builder"
description = "Tools & types for building with XCM and its executor."
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
impl-trait-for-tuples = "0.2.1"
parity-scale-codec = { version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
log = { version = "0.4.17", default-features = false }

# Polkadot dependencies
polkadot-parachain = { path = "../../parachain", default-features = false }

[dev-dependencies]
primitive-types = "0.12.1"
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
pallet-xcm = { path = "../pallet-xcm" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
assert_matches = "1.5.0"

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks"
]
std = [
	"log/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"xcm/std",
	"xcm-executor/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"polkadot-parachain/std",
	"pallet-transaction-payment/std",
]
