[package]
name = "polkadot-node-jaeger"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Polkadot Jaeger primitives, but equally useful for Grafana/Tempo"

[dependencies]
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.0"
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
thiserror = "1.0.31"
tokio = "1.24.2"
log = "0.4.17"
parity-scale-codec = { version = "3.4.0", default-features = false }
