[package]
name = "polkadot-node-core-pvf-prepare-worker-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "polkadot-prepare-worker"
path = "src/main.rs"

[dependencies]
polkadot-node-core-pvf-common = { path = "../../common" }
polkadot-node-core-pvf-prepare-worker = { path = "../" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }
