[package]
name = "test-parachain-undying"
description = "Test parachain for zombienet integration tests"
build = "build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
parachain = { package = "polkadot-parachain", path = "../../", default-features = false, features = [ "wasm-api" ] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.4", features = [ "global" ] }
log = { version = "0.4.17", default-features = false }

# We need to make sure the global allocator is disabled until we have support of full substrate externalities
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, features = [ "disable_allocator" ] , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", rev = "02334a851587e65542cec57a12c9c7201b330e2d" }

[features]
default = [ "std" ]
std = [
	"parachain/std",
	"sp-std/std",
]
