[package]
name = "polkadot-runtime-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
impl-trait-for-tuples = "0.2.2"
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.163", default-features = false, features = ["alloc"] }
serde_derive = { version = "1.0.117" }
static_assertions = "1.1.0"

sp-api = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
inherents = { package = "sp-inherents", git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
sp-std = { package = "sp-std", git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
sp-io = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
sp-runtime = { git = "https://github.com/melekes/substrate", default-features = false , features=["serde"], branch = "anton/kademlia-server-mode" }
sp-session = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
sp-staking = { git = "https://github.com/melekes/substrate", default-features = false, features=["serde"] , branch = "anton/kademlia-server-mode" }
sp-core = { git = "https://github.com/melekes/substrate", default-features = false , features=["serde"], branch = "anton/kademlia-server-mode" }
sp-npos-elections = { git = "https://github.com/melekes/substrate", default-features = false, features=["serde"] , branch = "anton/kademlia-server-mode" }

pallet-authorship = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-balances = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-fast-unstake = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-session = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
frame-support = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-staking = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-staking-reward-fn = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
frame-system = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-timestamp = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-vesting = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-transaction-payment = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-treasury = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
pallet-election-provider-multi-phase = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
frame-election-provider-support = { git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }

frame-benchmarking = { git = "https://github.com/melekes/substrate", default-features = false, optional = true , branch = "anton/kademlia-server-mode" }
pallet-babe = { git = "https://github.com/melekes/substrate", default-features = false, optional = true , branch = "anton/kademlia-server-mode" }

primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.7.0", default-features = false }
runtime-parachains = { package = "polkadot-runtime-parachains", path = "../parachains", default-features = false }

slot-range-helper = { path = "slot_range_helper", default-features = false }
xcm = { path = "../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.4.1"
frame-support-test = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
pallet-babe = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
pallet-treasury = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
sp-keystore = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
sp-keyring = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
serde_json = "1.0.96"
libsecp256k1 = "0.7.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../primitives/test-helpers" }

[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"log/std",
	"rustc-hex/std",
	"serde/std",
	"primitives/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"pallet-fast-unstake/std",
	"pallet-staking/std",
	"pallet-staking-reward-fn/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-election-provider-multi-phase/std",
	"slot-range-helper/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"frame-system/std",
	"libsecp256k1/std",
	"runtime-parachains/std",
	"xcm/std",
	"sp-npos-elections/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"libsecp256k1/static-context",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"runtime-parachains/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-fast-unstake/runtime-benchmarks"
]
try-runtime = [
	"runtime-parachains/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-fast-unstake/try-runtime",
]
