[package]
name = "polkadot-primitives-test-helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-keyring = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/melekes/substrate", default-features = false , branch = "anton/kademlia-server-mode" }
sp-runtime = { git = "https://github.com/melekes/substrate", branch = "anton/kademlia-server-mode" }
sp-core = { git = "https://github.com/melekes/substrate", features = ["std"] , branch = "anton/kademlia-server-mode" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
