[package]
name = "polkadot-primitives-test-helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"] , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
