[package]
name = "polkadot-primitives-test-helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"] , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
polkadot-primitives = { path = "../" }
rand = "0.8.5"
