[package]
name = "pallet-xcm"
authors.workspace = true
edition.workspace = true
version.workspace = true


[dependencies]
bounded-collections = { version = "0.1.5", default-features = false }
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
log = { version = "0.4.17", default-features = false }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }

xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "a03b9a01e59c3d4ce4b6bb7f1f9ca150898b054c" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
polkadot-parachain = { path = "../../parachain" }
xcm-builder = { path = "../xcm-builder" }

[features]
default = ["std"]
std = [
	"bounded-collections/std",
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-std/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"xcm/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
