[package]
name = "slot-range-helper"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
paste = "1.0"
enumn = "0.1.5"
parity-scale-codec = { version = "3.4.0", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "a0dcac4adafbe4e05d96ab86a71e793c89a73e46" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
