[package]
name = "slot-range-helper"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
paste = "1.0"
enumn = "0.1.8"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , rev = "02334a851587e65542cec57a12c9c7201b330e2d" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
