name: Release - Publish RC Container image
# see https://github.com/paritytech/release-engineering/issues/97#issuecomment-1651372277

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: 'Release ID'
        required: true
        type: string
      registry:
        description: "Container registry"
        required: true
        type: string
        default: docker.io/parity

env:
  RELEASE_ID: ${{ inputs.release_id }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # paritytech
  OWNER: ${{ github.repository_owner }}
  # polkadot
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Fetch all artifacts
        run: |
          . ./scripts/ci/common/lib.sh
          fetch_release_artifacts

  build-container:
    runs-on: ubuntu-latest
    needs: fetch-artifacts

    strategy:
      matrix:
        binary: ["polkadot", "staking-miner"]

    steps:
      - name: Check ${{ matrix.binary }}
        run: |
          echo "Checking binary ${{ matrix.binary }}"
          check_sha256 ${{ matrix.binary }}
          check_gpg ${{ matrix.binary }}

      - name: Build Injected Container image for ${{ matrix.binary }}
        run: |
          echo "Building container for ${{ matrix.binary }}"

      - name: Push Container image
        env:
          IMAGE: ${{ inputs.registry }}/${{ matrix.binary }}
        run: |
          echo "TODO Pushing image to $IMAGE"
